original_frames_directory: 'current_workspace\original_frames'
transparent_frames_directory: 'current_workspace\transparent_frames'
frames_with_background_color_directory: 'current_workspace\frames_with_background_color'
input_file: 'current_workspace\source.mp4'
output_file: 'current_workspace\result.mp4'
should_save_original_frames: true
should_save_transparent_frames: true
should_save_frames_with_background_color: true
background_color_red_amount: 0
background_color_green_amount: 0
background_color_blue_amount: 0
